### ISSUE TITLE
Running LIRA on sources with low counts in the core

### ISSUE THREAD

**Issue by infinitron** [astrostat/LIRA#2]
Hi,

I'm trying to use LIRA to detect X-ray sources from a region where there are only a few counts in the core. For example, the following source has 33 counts in the core region(bigger circle) and a few X-ray counts to the northeast (smaller circle; knot). 

![image](https://user-images.githubusercontent.com/4162508/67626577-04368c80-f81b-11e9-8ac7-d194fa60f358.png)

Now, if I generate a baseline model using a ```2d gaussian+ const background```, the resulting gaussian encompasses both the core and the knot. Running LIRA to detect the knot region would just give me an upper bound on the p-value of 1 which is not true in this case. I tried setting the location of the core manually and then fit a gaussian to it. The wings of the fitted gaussian would still contaminate the knot region thereby eliminating any possible detection using LIRA.

I'm not sure how to create a proper baseline model that correctly represents this under-exposed core. Should I set a limit on the fwhm of the fitted gaussian? Or should I go for a lower resolution model? The exposure is this region is almost the same in every pixel. I suppose passing it to LIRA won't make any big difference.

For reference, the simulated psf looks like this
![image](https://user-images.githubusercontent.com/4162508/67627062-19afb480-f823-11e9-9f1b-1d7d83a8c0c2.png)

I would appreciate any pointers to this issue.

Thanks,
Karthik

**Comment by vkashyap** [comment]
If I understand correctly, the problem seems to be that the 2D Gaussian part of your baseline model is too broad.  This can happen because of the spatial fitting procedure.  If you know that there is one point source where you have marked the 33-count core, then put a delta-function or a very narrow Gaussian (say N([0,0],[0.5^2,0.5^2]) at the putative location and compare against that.  LIRA looks for multi-scale signatures that are not explained by the baseline model.  If the fit is "good enough" already, then there is no need to add an additional component.

That said, if you are trying to disentangle the overlapping sources, and either measure the intensities separately or find a way to separate them and carry out spectral analyses independently, then you should look at Primini & Kashyap 2014 (ApJ 796, 24; https://iopscience.iop.org/article/10.1088/0004-637X/796/1/24/pdf) or Jones et al. 2015 (ApJ 808, 137; BASCS  -- https://github.com/astrostat/BASCS) respectively.

**Comment by infinitron** [comment]
Thanks! I've used a smaller Gaussian and I was able to infer the presence of an X-ray source. 

I have another question. Is there any way to obtain the location of the detected X-ray source from the fitted model? For example, I have an X-ray source detected somewhere along an extragalactic jet. What I would like to know is whether the location of the detected X-ray source is coincident with its radio counterpart or not. Does a maximum of the posterior inside a given region point to a possible location of the X-ray point source? (given that there are no other local maxima in this region? Also, my sources won't overlap).

This is an example output image from LIRA ([McKeough et al 2016](https://iopscience.iop.org/article/10.3847/1538-4357/833/1/123/pdf)). The upper bound on p-value is 0.005 for region 3. Would it be valid to assume that the location of the peak in region 3 is the most probable location of an X-ray point source located in this region?
![image](https://user-images.githubusercontent.com/4162508/69206535-f1159480-0b1a-11ea-81e3-e05a9b9295d8.png)

**Comment by vkashyap** [comment]
I don't have definitive answers to most of these questions, but here are some thoughts:

_Is there any way to obtain the location of the detected X-ray source from the fitted model?_

In the general case, I don't think it is possible to do so, because what LIRA is doing is estimating the intensity in each pixel that would produce the observed data for the given PSF and the supplied baseline.  If it were a point source, in principle all the signal will be limited to a single pixel.  Because there are a finite number of counts in any observation will spread this intensity around to account for Poisson fluctuations, but there is no way to distinguish that effect from a truly extended source.  

Now, if you have strong prior information that the source is point-like (or close enough to it), it is perfectly reasonable to compute an intensity weighted centroid and call it the location of the source.  But note that the ROI you would be using to extract these intensities likely comes the radio itself, so your estimate of a centroid will not be correct.  You will, however, be able to confirm it if the X-ray centroid _differs_ from the radio centroid.

_Does a maximum of the posterior inside a given region point to a possible location of the X-ray point source? (given that there are no other local maxima in this region? Also, my sources won't overlap)_
_Would it be valid to assume that the location of the peak in region 3 is the most probable location of an X-ray point source located in this region?_

The location of the maximum by itself will not.  You can see why by looking at the intensities in the surrounding pixels in the individual iterations.  There will be considerable fluctuations, which means that the location of the maximum will have some uncertainty which you will have to incorporate into your analysis.  Computing the intensity weighted centroid (either on the average image, or even better, on the iteration images), strikes me as a better way to do it.

Also note, the maximum of the image _intensity_ is not the same as the maximum posterior _probability._  The entire image is one draw in the MCMC chain.  You can construct posterior probability densities for each pixel individually, and their individual MAP values will not necessarily match with each other, or even occur in any iteration.

We are working on a method to define a boundary in the LIRA output for a source deemed to be detected.  You wouldn't be able to use that boundary to ask whether the source is detectable, but once you have a boundary, you could compute summaries of the pixel-wise intensities within the boundary which should answer your questions.  Keep an eye out for McKeough et al. 2020.

**Comment by infinitron** [comment]
Thanks a lot, those are some great pointers!
